export enum Permission {
  VIEW_ALL = 'VIEW_ALL',
  VIEW_ROLE_SCOPED = 'VIEW_ROLE_SCOPED',
  CREATE_MISSION = 'CREATE_MISSION',
  CREATE_QUEST = 'CREATE_QUEST',
  CREATE_TASK = 'CREATE_TASK',
  UPDATE_OWN_TASK = 'UPDATE_OWN_TASK',
  UPDATE_ANY_TASK = 'UPDATE_ANY_TASK',
  UPLOAD_EVIDENCE = 'UPLOAD_EVIDENCE',
  APPROVE_EVIDENCE = 'APPROVE_EVIDENCE',
  VERIFY_TASK = 'VERIFY_TASK',
  CREATE_DECISION = 'CREATE_DECISION',
  APPROVE_DECISION = 'APPROVE_DECISION',
  CREATE_ADHOC_TASK = 'CREATE_ADHOC_TASK',
  MANAGE_RBAC = 'MANAGE_RBAC',
  MANAGE_SYSTEM = 'MANAGE_SYSTEM',
  MANAGE_KPIS = 'MANAGE_KPIS',
  MANAGE_DELEGATIONS = 'MANAGE_DELEGATIONS',
  MANAGE_OPS = 'MANAGE_OPS',
}

export const PERMISSION_DISPLAY_NAMES: Record<Permission, string> = {
  [Permission.VIEW_ALL]: 'View all data',
  [Permission.VIEW_ROLE_SCOPED]: 'View own data',
  [Permission.CREATE_MISSION]: 'Create missions',
  [Permission.CREATE_QUEST]: 'Create quests',
  [Permission.CREATE_TASK]: 'Create tasks',
  [Permission.UPDATE_OWN_TASK]: 'Update own tasks',
  [Permission.UPDATE_ANY_TASK]: 'Update any task',
  [Permission.UPLOAD_EVIDENCE]: 'Upload evidence',
  [Permission.APPROVE_EVIDENCE]: 'Approve evidence',
  [Permission.VERIFY_TASK]: 'Verify tasks',
  [Permission.CREATE_DECISION]: 'Log decisions',
  [Permission.APPROVE_DECISION]: 'Approve decisions',
  [Permission.CREATE_ADHOC_TASK]: 'Inject ad-hoc tasks',
  [Permission.MANAGE_RBAC]: 'Manage permissions',
  [Permission.MANAGE_SYSTEM]: 'Manage system',
  [Permission.MANAGE_KPIS]: 'Manage KPIs',
  [Permission.MANAGE_DELEGATIONS]: 'Manage approval delegations',
  [Permission.MANAGE_OPS]: 'Manage operations',
};

export const PERMISSION_DESCRIPTIONS: Record<Permission, string> = {
  [Permission.VIEW_ALL]: 'See data across all users and roles',
  [Permission.VIEW_ROLE_SCOPED]: 'See only data assigned to this role',
  [Permission.CREATE_MISSION]: 'Create long-term missions and phases',
  [Permission.CREATE_QUEST]: 'Create weekly quests within missions',
  [Permission.CREATE_TASK]: 'Create daily tasks within quests',
  [Permission.UPDATE_OWN_TASK]: 'Edit tasks assigned to this user',
  [Permission.UPDATE_ANY_TASK]: 'Edit tasks assigned to any user',
  [Permission.UPLOAD_EVIDENCE]: 'Attach proof to completed tasks',
  [Permission.APPROVE_EVIDENCE]: 'Review and approve/reject submitted evidence',
  [Permission.VERIFY_TASK]: 'Mark a task as verified (final validation)',
  [Permission.CREATE_DECISION]: 'Record team decisions with context',
  [Permission.APPROVE_DECISION]: 'Sign off on pending decisions',
  [Permission.CREATE_ADHOC_TASK]: 'Add unplanned tasks to active quests',
  [Permission.MANAGE_RBAC]: 'Change role permissions from this screen',
  [Permission.MANAGE_SYSTEM]: 'Access system configuration and settings',
  [Permission.MANAGE_KPIS]: 'Create and edit KPI metrics',
  [Permission.MANAGE_DELEGATIONS]: 'Create and deactivate approval delegations between users',
  [Permission.MANAGE_OPS]: 'Create and manage zones, brands, channels, and assets',
};
