[build]
builder = "nixpacks"
buildCommand = "npx prisma migrate deploy && npx prisma generate && npm run build"
watchPatterns = ["backend/**"]

[deploy]
startCommand = "node dist/src/main.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
