'use client';

import { useState, useMemo } from 'react';
import { useQuery } from '@tanstack/react-query';
import { AlertCircle } from 'lucide-react';
import { Input } from '@/components/ui/input';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  Table,
  TableHeader,
  TableRow,
  TableHead,
} from '@/components/ui/table';
import { apiClient } from '@/lib/api-client';
import { EXPORT_TYPE_CONFIG, type ExportRecord, type ReportType } from '@/lib/types/exports';
import { ExportHistoryTable } from '@/components/ops/exports/ExportHistoryTable';
import { ExportHistorySkeleton } from '@/components/ops/exports/ExportHistorySkeleton';

const sortedReportTypes = (Object.entries(EXPORT_TYPE_CONFIG) as [ReportType, { label: string }][])
  .sort((a, b) => a[1].label.localeCompare(b[1].label));

export default function AdminExportsPage() {
  const [reportType, setReportType] = useState('');
  const [dateFrom, setDateFrom] = useState('');
  const [dateTo, setDateTo] = useState('');

  const queryParams = useMemo(() => {
    const params = new URLSearchParams();
    if (reportType) params.set('reportType', reportType);
    if (dateFrom) params.set('dateFrom', dateFrom);
    if (dateTo) params.set('dateTo', dateTo);
    const qs = params.toString();
    return qs ? `?${qs}` : '';
  }, [reportType, dateFrom, dateTo]);

  const { data, isLoading, isError } = useQuery({
    queryKey: ['exports', 'history', reportType, dateFrom, dateTo],
    queryFn: () => apiClient.get<ExportRecord[]>(`/exports/history${queryParams}`),
  });

  return (
    <div className="space-y-6">
      {/* Page header */}
      <div>
        <h1 className="text-2xl font-bold">Exports</h1>
        <p className="text-sm text-muted-foreground">
          Download history and re-export any report.
        </p>
      </div>

      {/* Filter bar */}
      <div className="flex items-center gap-3 flex-wrap">
        <Select
          value={reportType}
          onValueChange={(v: string | null) => setReportType(v ?? '')}
        >
          <SelectTrigger className="w-48">
            <SelectValue placeholder="All report types" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="">All report types</SelectItem>
            {sortedReportTypes.map(([key, config]) => (
              <SelectItem key={key} value={key}>
                {config.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        <div className="space-y-1">
          <label className="text-xs font-bold text-muted-foreground">From</label>
          <Input
            type="date"
            value={dateFrom}
            onChange={(e) => setDateFrom(e.target.value)}
            className="w-36"
          />
        </div>
        <div className="space-y-1">
          <label className="text-xs font-bold text-muted-foreground">To</label>
          <Input
            type="date"
            value={dateTo}
            onChange={(e) => setDateTo(e.target.value)}
            className="w-36"
          />
        </div>
      </div>

      {/* Loading state */}
      {isLoading && (
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="text-sm text-muted-foreground">Report Type</TableHead>
              <TableHead className="text-sm text-muted-foreground">Format</TableHead>
              <TableHead className="text-sm text-muted-foreground">Filters Applied</TableHead>
              <TableHead className="text-sm text-muted-foreground">File Size</TableHead>
              <TableHead className="text-sm text-muted-foreground">Generated By</TableHead>
              <TableHead className="text-sm text-muted-foreground">Generated At</TableHead>
              <TableHead className="text-sm text-muted-foreground">Status</TableHead>
              <TableHead className="w-[80px]">
                <span className="sr-only">Actions</span>
              </TableHead>
            </TableRow>
          </TableHeader>
          <ExportHistorySkeleton />
        </Table>
      )}

      {/* Error state */}
      {isError && (
        <div className="flex items-center gap-2 py-8 justify-center text-sm text-muted-foreground">
          <AlertCircle className="size-4 text-destructive" />
          Could not load export history. Try refreshing the page.
        </div>
      )}

      {/* Data */}
      {data && <ExportHistoryTable records={data} />}
    </div>
  );
}
