'use client';

import { Download, FileSpreadsheet, FileText, Loader2 } from 'lucide-react';
import { formatDistanceToNow } from 'date-fns';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip';
import { ExportStatusBadge } from './ExportStatusBadge';
import { EXPORT_TYPE_CONFIG } from '@/lib/types/exports';
import type { ExportRecord } from '@/lib/types/exports';

function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${Math.round(bytes / 1024)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function getReportLabel(reportType: string): string {
  const config = EXPORT_TYPE_CONFIG[reportType as keyof typeof EXPORT_TYPE_CONFIG];
  return config?.label ?? reportType;
}

interface ExportHistoryTableProps {
  records: ExportRecord[];
}

export function ExportHistoryTable({ records }: ExportHistoryTableProps) {
  if (records.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-16 space-y-4 text-center">
        <Download className="size-16 text-muted-foreground/40" />
        <div className="space-y-1">
          <h2 className="text-xl font-semibold">No exports yet</h2>
          <p className="text-sm text-muted-foreground">
            Exports appear here after you download a report from any data page.
          </p>
        </div>
      </div>
    );
  }

  return (
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead className="text-sm text-muted-foreground">Report Type</TableHead>
          <TableHead className="text-sm text-muted-foreground">Format</TableHead>
          <TableHead className="text-sm text-muted-foreground">Filters Applied</TableHead>
          <TableHead className="text-sm text-muted-foreground">File Size</TableHead>
          <TableHead className="text-sm text-muted-foreground">Generated By</TableHead>
          <TableHead className="text-sm text-muted-foreground">Generated At</TableHead>
          <TableHead className="text-sm text-muted-foreground">Status</TableHead>
          <TableHead className="w-[80px]">
            <span className="sr-only">Actions</span>
          </TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        {records.map((record) => (
          <TableRow key={record.id} className="hover:bg-muted/50">
            <TableCell className="text-sm">{getReportLabel(record.report_type)}</TableCell>
            <TableCell>
              <Badge variant="secondary" className="text-sm gap-1">
                {record.format === 'xlsx' ? (
                  <FileSpreadsheet className="size-3" />
                ) : (
                  <FileText className="size-3" />
                )}
                {record.format.toUpperCase()}
              </Badge>
            </TableCell>
            <TableCell
              className="text-sm text-muted-foreground max-w-[160px] truncate"
              title={record.filters_applied ?? ''}
            >
              {record.filters_applied ?? '\u2014'}
            </TableCell>
            <TableCell className="text-sm text-muted-foreground">
              {formatFileSize(record.file_size_bytes)}
            </TableCell>
            <TableCell className="text-sm text-muted-foreground">
              {record.user?.name ?? '\u2014'}
            </TableCell>
            <TableCell className="text-sm text-muted-foreground">
              {formatDistanceToNow(new Date(record.created_at))} ago
            </TableCell>
            <TableCell>
              <ExportStatusBadge status={record.status} />
            </TableCell>
            <TableCell className="w-[80px] text-right">
              {record.status === 'completed' && (
                <TooltipProvider delay={400}>
                  <Tooltip>
                    <TooltipTrigger
                      render={
                        <Button
                          variant="ghost"
                          size="icon"
                          onClick={() => window.open(record.download_url, '_blank')}
                          aria-label={`Re-download ${getReportLabel(record.report_type)} export`}
                        />
                      }
                    >
                      <Download className="size-4" />
                    </TooltipTrigger>
                    <TooltipContent side="left">Re-download</TooltipContent>
                  </Tooltip>
                </TooltipProvider>
              )}
              {record.status === 'generating' && (
                <Button
                  variant="ghost"
                  size="icon"
                  disabled
                  className="opacity-40 cursor-not-allowed"
                  aria-label="Export in progress"
                >
                  <Loader2 className="size-4 animate-spin" />
                </Button>
              )}
            </TableCell>
          </TableRow>
        ))}
      </TableBody>
    </Table>
  );
}
