'use client';

import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ApprovalQueue } from '@/components/ops/approvals/ApprovalQueue';
import { apiClient } from '@/lib/api-client';
import type { Approval, ApprovalEntityType } from '@/lib/types/approvals';

type EntityFilter = 'all' | ApprovalEntityType;

const TABS: { value: EntityFilter; label: string }[] = [
  { value: 'all', label: 'All' },
  { value: 'task', label: 'Tasks' },
  { value: 'recipe', label: 'Recipes' },
  { value: 'decision', label: 'Decisions' },
  { value: 'evidence', label: 'Evidence' },
];

export default function ApprovalsPage() {
  const queryClient = useQueryClient();
  const [entityFilter, setEntityFilter] = useState<EntityFilter>('all');

  /**
   * SPEC §6.2 — the inbox is `Approval` rows generated by the policy engine, not
   * evidence. One query owns the list; the header badge counts the same rows so
   * the page never fetches the queue twice.
   */
  const { data, isLoading, isError } = useQuery({
    queryKey: ['approvals', 'pending', entityFilter],
    queryFn: () =>
      apiClient.get<Approval[]>(
        `/approvals?mine=1&status=pending${
          entityFilter === 'all' ? '' : `&entity_type=${entityFilter}`
        }`,
      ),
  });

  const pendingCount = data?.length ?? 0;

  const handleAction = () => {
    void queryClient.invalidateQueries({ queryKey: ['approvals'] });
  };

  return (
    <div className="space-y-6">
      {/* Page header */}
      <div className="space-y-1">
        <div className="flex items-center gap-3">
          <h1 className="text-2xl font-bold text-ink">Approvals</h1>
          {pendingCount > 0 && (
            <Badge
              variant="outline"
              className="border-warning/30 bg-warning/12 text-warning"
            >
              {pendingCount} pending
            </Badge>
          )}
        </div>
        <p className="text-sm text-ink-muted">
          Everything waiting on your sign-off — tasks, recipes, decisions and
          evidence.
        </p>
      </div>

      {/* Entity filter tabs */}
      <Tabs
        value={entityFilter}
        onValueChange={(value) => setEntityFilter(value as EntityFilter)}
      >
        <TabsList className="max-w-full overflow-x-auto">
          {TABS.map((tab) => (
            <TabsTrigger key={tab.value} value={tab.value}>
              {tab.label}
            </TabsTrigger>
          ))}
        </TabsList>
      </Tabs>

      {/* Approval queue */}
      <ApprovalQueue
        approvals={data ?? []}
        isLoading={isLoading}
        isError={isError}
        groupByEntity={entityFilter === 'all'}
        onAction={handleAction}
      />
    </div>
  );
}
